repos:
  - repo: local
    hooks:
      - id: system
        name: black
        entry: pdm run black toaduanki/
        language: system
        types: [python]
      - id: system
        name: isort
        entry: pdm run isort toaduanki/
        language: system
        types: [python]
      - id: system
        name: flake8
        entry: pdm run flake8 toaduanki/
        language: system
        types: [python]
